name: Add Pull Requests Labels
on: 
    pull_request_target: 
        types: [opened, closed, ready_for_review]

jobs:
    add-labels:
        timeout-minutes: 5
        runs-on: ubuntu-latest
        
        if: github.event.action == 'opened'
        permissions: 
            contents: read
            pull-requests: write
        
        steps:
            - uses: actions/labeler@v6
